// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/olympus/v1/c2.proto

package olympusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentsRequest) Reset() {
	*x = GetAgentsRequest{}
	mi := &file_proto_olympus_v1_c2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentsRequest) ProtoMessage() {}

func (x *GetAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_olympus_v1_c2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_olympus_v1_c2_proto_rawDescGZIP(), []int{0}
}

type GetAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentsResponse) Reset() {
	*x = GetAgentsResponse{}
	mi := &file_proto_olympus_v1_c2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentsResponse) ProtoMessage() {}

func (x *GetAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_olympus_v1_c2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_olympus_v1_c2_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LastSeen      string                 `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_olympus_v1_c2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_olympus_v1_c2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_olympus_v1_c2_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

var File_proto_olympus_v1_c2_proto protoreflect.FileDescriptor

const file_proto_olympus_v1_c2_proto_rawDesc = "" +
	"\n" +
	"\x19proto/olympus/v1/c2.proto\x12\n" +
	"olympus.v1\"\x12\n" +
	"\x10GetAgentsRequest\">\n" +
	"\x11GetAgentsResponse\x12)\n" +
	"\x06agents\x18\x01 \x03(\v2\x11.olympus.v1.AgentR\x06agents\"P\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\tR\blastSeen2Z\n" +
	"\x0eOlympusService\x12H\n" +
	"\tGetAgents\x12\x1c.olympus.v1.GetAgentsRequest\x1a\x1d.olympus.v1.GetAgentsResponseB;Z9github.com/NotKidding/olympus-server/pkg/api/v1;olympusv1b\x06proto3"

var (
	file_proto_olympus_v1_c2_proto_rawDescOnce sync.Once
	file_proto_olympus_v1_c2_proto_rawDescData []byte
)

func file_proto_olympus_v1_c2_proto_rawDescGZIP() []byte {
	file_proto_olympus_v1_c2_proto_rawDescOnce.Do(func() {
		file_proto_olympus_v1_c2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_olympus_v1_c2_proto_rawDesc), len(file_proto_olympus_v1_c2_proto_rawDesc)))
	})
	return file_proto_olympus_v1_c2_proto_rawDescData
}

var file_proto_olympus_v1_c2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_olympus_v1_c2_proto_goTypes = []any{
	(*GetAgentsRequest)(nil),  // 0: olympus.v1.GetAgentsRequest
	(*GetAgentsResponse)(nil), // 1: olympus.v1.GetAgentsResponse
	(*Agent)(nil),             // 2: olympus.v1.Agent
}
var file_proto_olympus_v1_c2_proto_depIdxs = []int32{
	2, // 0: olympus.v1.GetAgentsResponse.agents:type_name -> olympus.v1.Agent
	0, // 1: olympus.v1.OlympusService.GetAgents:input_type -> olympus.v1.GetAgentsRequest
	1, // 2: olympus.v1.OlympusService.GetAgents:output_type -> olympus.v1.GetAgentsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_olympus_v1_c2_proto_init() }
func file_proto_olympus_v1_c2_proto_init() {
	if File_proto_olympus_v1_c2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_olympus_v1_c2_proto_rawDesc), len(file_proto_olympus_v1_c2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_olympus_v1_c2_proto_goTypes,
		DependencyIndexes: file_proto_olympus_v1_c2_proto_depIdxs,
		MessageInfos:      file_proto_olympus_v1_c2_proto_msgTypes,
	}.Build()
	File_proto_olympus_v1_c2_proto = out.File
	file_proto_olympus_v1_c2_proto_goTypes = nil
	file_proto_olympus_v1_c2_proto_depIdxs = nil
}
