// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/olympus/v1/c2.proto

package olympusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OlympusService_GetAgents_FullMethodName = "/olympus.v1.OlympusService/GetAgents"
)

// OlympusServiceClient is the client API for OlympusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OlympusServiceClient interface {
	// For Role C to get the agent list
	GetAgents(ctx context.Context, in *GetAgentsRequest, opts ...grpc.CallOption) (*GetAgentsResponse, error)
}

type olympusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOlympusServiceClient(cc grpc.ClientConnInterface) OlympusServiceClient {
	return &olympusServiceClient{cc}
}

func (c *olympusServiceClient) GetAgents(ctx context.Context, in *GetAgentsRequest, opts ...grpc.CallOption) (*GetAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentsResponse)
	err := c.cc.Invoke(ctx, OlympusService_GetAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OlympusServiceServer is the server API for OlympusService service.
// All implementations must embed UnimplementedOlympusServiceServer
// for forward compatibility.
type OlympusServiceServer interface {
	// For Role C to get the agent list
	GetAgents(context.Context, *GetAgentsRequest) (*GetAgentsResponse, error)
	mustEmbedUnimplementedOlympusServiceServer()
}

// UnimplementedOlympusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOlympusServiceServer struct{}

func (UnimplementedOlympusServiceServer) GetAgents(context.Context, *GetAgentsRequest) (*GetAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgents not implemented")
}
func (UnimplementedOlympusServiceServer) mustEmbedUnimplementedOlympusServiceServer() {}
func (UnimplementedOlympusServiceServer) testEmbeddedByValue()                        {}

// UnsafeOlympusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OlympusServiceServer will
// result in compilation errors.
type UnsafeOlympusServiceServer interface {
	mustEmbedUnimplementedOlympusServiceServer()
}

func RegisterOlympusServiceServer(s grpc.ServiceRegistrar, srv OlympusServiceServer) {
	// If the following call panics, it indicates UnimplementedOlympusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OlympusService_ServiceDesc, srv)
}

func _OlympusService_GetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlympusServiceServer).GetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlympusService_GetAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlympusServiceServer).GetAgents(ctx, req.(*GetAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OlympusService_ServiceDesc is the grpc.ServiceDesc for OlympusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OlympusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olympus.v1.OlympusService",
	HandlerType: (*OlympusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgents",
			Handler:    _OlympusService_GetAgents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/olympus/v1/c2.proto",
}
